### ISSUE TITLE
Using Kinesalite for local Java integration tests

### ISSUE THREAD

**Issue by tzulitai** [mhart/kinesalite#26]
Hi, may you provide some tips on using Kinesalite to setup integration tests for Java projects?

Thanks for this development!

**Comment by mhart** [comment]
I'd just execute kinesalite from Java like any other system process. It's been a while since I've done Java, but I assume that means using https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#exec(java.lang.String) or https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html

Then when you're done with your tests, shut it down.
