### ISSUE TITLE
Add Support for Initial Streams

### ISSUE THREAD

**Issue by AdrieanKhisbe** [mhart/kinesalite#52]
It would be great if you could pass some initial streams configuration as an option to the kinesalite server.

For instance `kinesalite --streams='{"stream1": 1, "stream2": 2}'`.

I have wrote a wrapper script that present this feature, but that would be nice to support it natively.
(I'll be happy to share the script, which rely on the aws sdk to create the stream)

**Comment by TJC** [comment]
For those of you wondering how to do this at home, I ended up with:
```sh
kinesalite --ssl
aws --no-verify-ssl --endpoint-url=https://localhost:4567 kinesis \
    create-stream --stream-name my-stream-name --shard-count 1
```

**Comment by mhart** [comment]
Not going to add this for now – it's pretty trivial just to use the AWS CLI or similar to achieve this. Thanks for the idea though!

**Comment by 5er9e1** [comment]
> it's pretty trivial just to use the AWS CLI or similar to achieve this

Yes, trivial thing that is being a huge bottle neck all this time. Let's suppose that I want to run automated test at GitHub Actions. What I need to do now:
- Download a more or less heavy Debian docker image (AWS CLI doesn't work with Alpine because it is compiled with glibC)
- Wait until kinesalite container will be ready for connections
- Build AWS CLI container using Debian image
- Run AWS CLI container to create stream

One simple parameter argument that can replace minutes of fragile build process.
